services:
  app:
    build: .
    container_name: e-teckw
    environment:
      - DATABASE_URL=postgresql://${USER}:${PASSWORD}@db:5432/${DB}?schema=public
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - teckw-net

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER} -d ${DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - teckw-net

volumes:
  postgres-data:

networks:
  teckw-net:
    driver: bridge
